### PR TITLE
Migrate from Travis-CI to Github Actions

### PR DESCRIPTION
**Pull request by liry**
Since Maven is not supported by Coveralls GH Action,
we also need to migrate coverage to Codecov.

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by sadam21** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-rest-common-merge-compliance-check/45/ : SUCCESS in 17s
- https://checklist.intgdc.com/job/compliance/job/gooddata-rest-common-fossa-scanning-zuul-el7/7/ : FAILURE in 2m 32s (non-voting)

**Pull request merged**
