### PR TITLE
INFRA-176: Add sonar properties - configuration for sonarcloud

### PR DESCRIPTION
**Pull request by tomaso**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by sadam21** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-rest-common-merge-compliance-check/79/ : SUCCESS in 21s
- https://checklist.intgdc.com/job/compliance/job/gooddata-rest-common-fossa-scanning-zuul/1/ : SUCCESS in 1m 15s (non-voting)

**Pull request merged**
